# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-11 19:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Praticien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('praticien_first_name', models.CharField(max_length=120)),
                ('praticien_last_name', models.CharField(max_length=120)),
                ('praticien_phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be like 06XXXXXXXX', regex='^0\\d{9}$')])),
                ('praticien_email', models.EmailField(max_length=254)),
                ('praticien_job', models.CharField(max_length=120)),
                ('praticien_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('praticien_introduction', models.TextField(blank=True, null=True)),
                ('praticien_formation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
