# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_CLIENTPAGE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='praticien_url_rdv',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
