# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_CLIENTPAGE', '0002_praticien_praticien_url_rdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='praticien_experiences_pro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
