# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_CLIENTPAGE', '0003_praticien_praticien_experiences_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=120)),
                ('office_adresse', models.CharField(max_length=300)),
                ('office_acces', models.TextField(blank=True, null=True)),
                ('office_description', models.TextField(blank=True, null=True)),
                ('office_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
