# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_CLIENTPAGE', '0004_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actcategory_name', models.CharField(max_length=120)),
                ('actcategory_short_description', models.TextField(blank=True, null=True)),
                ('actcategory_long_description', models.TextField(blank=True, null=True)),
                ('actcategory_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('actcategory_slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
