# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_CLIENTPAGE', '0005_actcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actcategory',
            old_name='actcategory_slug',
            new_name='slug',
        ),
    ]
