# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_CLIENTPAGE', '0006_auto_20180712_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name_small', models.CharField(max_length=120)),
                ('act_name_long', models.CharField(max_length=120)),
                ('act_description', models.TextField(blank=True, null=True)),
                ('act_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Act',
                'verbose_name_plural': 'Acts',
            },
        ),
        migrations.AlterModelOptions(
            name='actcategory',
            options={'verbose_name': 'Act category', 'verbose_name_plural': 'Acts categories'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Le cabinet', 'verbose_name_plural': 'Le cabinet'},
        ),
        migrations.AlterModelOptions(
            name='praticien',
            options={'verbose_name': 'Le praticien', 'verbose_name_plural': 'Le praticien'},
        ),
        migrations.AddField(
            model_name='act',
            name='act_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acte', to='APP_001_CLIENTPAGE.ActCategory'),
        ),
    ]
