# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-13 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_CLIENTPAGE', '0007_auto_20180712_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='act_image',
        ),
    ]
