# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_CLIENTPAGE', '0010_auto_20180714_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='actimage',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='act_name_long',
            field=models.CharField(help_text="Titre de l'article", max_length=120),
        ),
        migrations.AlterField(
            model_name='act',
            name='act_name_small',
            field=models.CharField(help_text='Texte de la barre de navigation', max_length=120),
        ),
        migrations.AlterField(
            model_name='act',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='actcategory',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
