# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_CLIENTPAGE', '0013_auto_20180714_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
