# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-14 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_CLIENTPAGE', '0014_praticien_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='office_description',
        ),
        migrations.RemoveField(
            model_name='office',
            name='office_image',
        ),
    ]
