# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-15 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_002_PROPAGE', '0002_patient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
