# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP_002_PROPAGE', '0004_auto_20180722_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=300)),
                ('zip_code', models.CharField(default='69960', max_length=5)),
                ('city', models.CharField(default='Corbas', max_length=64)),
                ('contry', models.CharField(default='France', max_length=64)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APP_002_PROPAGE.Adress'),
        ),
    ]
