# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-23 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_002_PROPAGE', '0006_auto_20180723_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='address_1',
            new_name='patient_address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='city',
            new_name='patient_city',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='contry',
            new_name='patient_contry',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='zip_code',
            new_name='patient_zip_code',
        ),
    ]
