# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-23 15:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP_002_PROPAGE', '0007_auto_20180723_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_address',
            field=models.CharField(max_length=300, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_city',
            field=models.CharField(default='Corbas', max_length=64, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_contry',
            field=models.CharField(default='France', max_length=64, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_first_name',
            field=models.CharField(max_length=120, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_last_name',
            field=models.CharField(max_length=120, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be like 06XXXXXXXX', regex='^0\\d{9}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_zip_code',
            field=models.CharField(default='69960', max_length=5, verbose_name='Code postal'),
        ),
    ]
