# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-23 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_002_PROPAGE', '0008_auto_20180723_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
