# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-23 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_002_PROPAGE', '0009_patient_patient_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_note',
            field=models.TextField(blank=True, default='Pas de remarques', null=True),
        ),
    ]
