# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-25 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_002_PROPAGE', '0010_auto_20180723_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_note',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_maiden_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nom de jeune fille'),
        ),
    ]
