# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-25 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_002_PROPAGE', '0011_auto_20180725_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_situation',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('en_couple', 'En couple'), ('mariee', 'Mariée')], default='celibataire', max_length=100),
        ),
    ]
