# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-25 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_002_PROPAGE', '0013_auto_20180725_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_zip_code',
            field=models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Code postal'),
        ),
    ]
