# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-25 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_002_PROPAGE', '0015_auto_20180725_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_FCV_bool',
            field=models.BooleanField(default=False, verbose_name='FCV'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_FCV_com',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='FCV informations'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_addictions',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tabac/addications'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_allergies',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Allergie(s)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_ant_chir',
            field=models.TextField(blank=True, null=True, verbose_name='Antécédants chirurgicaux'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_ant_fam',
            field=models.TextField(blank=True, null=True, verbose_name='Antécédants familiaux'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_ant_gyn',
            field=models.TextField(blank=True, null=True, verbose_name='Antécédants gynécologiques'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_ant_perso',
            field=models.TextField(blank=True, null=True, verbose_name='Antécédants personnels'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_contraception',
            field=models.CharField(blank=True, choices=[('rien', 'Pas de contraception'), ('anneau_vaginal', 'Anneau vignal'), ('DIU', 'DIU'), ('implant', 'Implant contraceptif'), ('ligature', 'Ligature des trompes'), ('obturation', 'Obturation des trompes'), ('patch', 'Patch'), ('pilule', 'Pilule contraceptive'), ('progestatif_en_injection', 'Progestatifs en injections')], default='rien', max_length=100, null=True, verbose_name='Contraception'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_poid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Poids (Kg)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_taille',
            field=models.FloatField(blank=True, null=True, verbose_name='Taille (m)'),
        ),
    ]
