# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-25 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_002_PROPAGE', '0017_patient_patient_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
