# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-27 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_002_PROPAGE', '0018_auto_20180725_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_situation',
            field=models.CharField(blank=True, choices=[('Célibataire', 'Célibataire'), ('En couple', 'En couple'), ('Mariée', 'Mariée')], default='Célibataire', max_length=100, null=True, verbose_name='Situation familiale'),
        ),
    ]
