# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 16:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfosProfessionnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('job', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be like +33XXXXXXXXX', regex='^\\+33\\d{9}$')])),
                ('email', models.EmailField(max_length=254)),
                ('pro_adress', models.CharField(max_length=300)),
            ],
        ),
    ]
