# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 15:48
from __future__ import unicode_literals

import APP_001_LANDINGPAGE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_LANDINGPAGE', '0002_auto_20180704_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesActes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image_carousel', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=APP_001_LANDINGPAGE.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='infosprofessionnelles',
            name='phone_number_p',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
    ]
